In [1]:
import os
import pandas as pd
import numpy as np

In [11]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\전처리')
df_19 = pd.read_csv('2019_타자_Saber.csv', encoding = 'cp949')
df_19.index = df_19['Name']
del df_19['Name']
df_19 = df_19[df_19['PA'] >= 144]
df_19 = df_19.drop(['RC', 'RC27', 'PSR'], axis = 1)
df_19

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,OBP,SLG,OPS,GPA,SECA,TA,XR,ISO,wOBA,BABIP
Name,,,,,,,,,,,,,,,,,,,,,
이대호,549,485,88,48,138,23,1,16,0,0,...,0.355191,0.435052,0.790243,0.268599,0.329897,0.732240,72.470,0.150515,0.639070,0.296837
박병호,532,432,98,92,121,22,0,33,0,1,...,0.398496,0.560185,0.958681,0.319370,0.585648,1.043887,98.344,0.280093,0.770666,0.302405
양의지,459,390,68,61,138,26,0,20,4,3,...,0.437908,0.574359,1.012267,0.340649,0.464103,1.085821,88.726,0.220513,0.802156,0.354354
손아섭,568,512,63,78,151,22,1,10,13,8,...,0.359788,0.400391,0.760179,0.262002,0.281250,0.722667,73.324,0.105469,0.588717,0.342233
최형우,555,456,86,65,137,31,1,17,0,1,...,0.412613,0.484649,0.897262,0.306838,0.475877,0.939940,90.714,0.184211,0.698233,0.325203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
나종덕,209,185,13,12,23,4,0,3,0,0,...,0.188119,0.194595,0.382713,0.133302,0.156757,0.305389,4.186,0.070270,1.335876,0.208333
허일,162,149,17,14,38,4,0,1,2,1,...,0.314815,0.302013,0.616828,0.217170,0.167785,0.530973,14.696,0.046980,1.629840,0.308333
이우성,168,151,22,19,33,4,0,6,0,0,...,0.281437,0.364238,0.645676,0.217706,0.291391,0.570248,16.510,0.145695,1.649287,0.252336
오윤석,228,198,21,21,44,2,0,1,0,0,...,0.294643,0.247475,0.542118,0.194458,0.141414,0.449367,16.726,0.025253,1.197368,0.272152
노시환,192,177,13,19,33,8,1,1,2,2,...,0.240838,0.259887,0.500725,0.173349,0.192090,0.409396,9.644,0.073446,1.409419,0.304762

In [14]:
df_19['wOBA']

Name
이대호    0.639070
박병호    0.770666
양의지    0.802156
손아섭    0.588717
최형우    0.698233
         ...
나종덕    1.335876
허일     1.629840
이우성    1.649287
오윤석    1.197368
노시환    1.409419
Name: wOBA, Length: 106, dtype: float64