In [1]:
import os
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\수비율\전처리')
df_1 = pd.read_csv('2019_전포지션_수비지표_합계_동명이인_추가.csv', encoding = 'cp949')
df_1.index = df_1['선수명']
del df_1['선수명']
df_1 = df_1.drop(columns = ['G', 'GS', 'PKO', 'PB', 'SB', 'CS'])
df_1

          IP   E   PO    A  DP      FPCT   팀명  포지션 수
선수명
강경학   273.00   4  121   68  31  0.979275   한화      3
강로한   709.67  20  123  235  51  0.947090   롯데      3
강민국   245.67   9   51   81  10  0.936170   KT      3
강민호   842.00   8  660   48   7  0.988827   삼성      1
강백호   622.66   3  140    6   1  0.979866   KT      5
..       ...  ..  ...  ...  ..       ...  ...    ...
홍창기    52.00   0   12    1   0  1.000000   LG      3
황대인    48.00   0   40    4   6  1.000000  KIA      2
황윤호   297.67   6   49   81  14  0.955882  KIA      3
황재균  1026.67  11  127  233  27  0.970350   KT      3
황진수    10.33   0    0    1   1  1.000000   롯데      2

[283 rows x 8 columns]

In [3]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\전처리')
saber = pd.read_csv('2019_타자_Saber.csv', encoding = 'cp949')
saber.index = saber['Name']
del saber['Name']
saber

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,SECA,TA,RC,RC27,XR,ISO,PSR,wOBA,BABIP,OW%
Name,,,,,,,,,,,,,,,,,,,,,
이정후,630,574,68,91,193,31,10,6,13,7,...,0.29094,0.80397,95.03027,3.51964,92.560,0.12021,8.21053,0.53310,0.35150,0.96536
김하성,625,540,104,112,166,38,2,19,33,4,...,0.47593,0.96154,96.32271,3.56751,104.670,0.18333,24.11538,0.62520,0.32813,0.96626
정은원,624,564,57,83,148,27,6,8,14,7,...,0.28191,0.63636,58.53332,2.1679,69.292,0.11170,10.18182,0.53814,0.30369,0.91360
이천웅,613,546,48,88,168,24,3,2,21,10,...,0.24359,0.71571,71.92514,2.66389,75.394,0.06593,3.65217,0.53459,0.35853,0.94106
최정,606,503,99,86,147,27,0,29,3,2,...,0.47714,0.99171,95.73611,3.54578,107.064,0.22664,5.43750,0.67752,0.30256,0.96586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
박상언,1,1,0,0,0,0,0,0,0,0,...,0,0.00000,-0.20667,-0.00765,-0.098,0.00000,NaN,247.77700,NaN,0.00013
추재현,1,1,0,0,0,0,0,0,0,0,...,0,0.00000,-0.1,-0.0037,-0.090,0.00000,NaN,247.77700,0.00000,0.00003
김주형,1,1,0,0,0,0,0,0,0,0,...,0,0.00000,-0.1,-0.0037,-0.090,0.00000,NaN,247.77700,0.00000,0.00003
양우현,1,1,0,0,0,0,0,0,0,0,...,0,0.00000,-0.1,-0.0037,-0.090,0.00000,NaN,247.77700,0.00000,0.00003
김태근,0,0,0,2,0,0,0,0,1,2,...,#NAME?,0.50000,#NAME?,#NAME?,-0.460,NaN,0.00000,inf,NaN,NaN

In [4]:
A_list = []
# B_list = []
for a in df_1.index.to_list() :
    if a in saber.index.to_list() :
        A_list.append(a)

# for b in saber['Name'] :
#     if b in df_1.index :
#         B_list.append(b)

In [5]:
## 수비만 있는 선수 제외
on_dfn = df_1.index.drop(A_list).to_list()
df_2 = df_1.drop(on_dfn)
df_2

          IP   E   PO    A  DP      FPCT   팀명  포지션 수
선수명
강경학   273.00   4  121   68  31  0.979275   한화      3
강로한   709.67  20  123  235  51  0.947090   롯데      3
강민국   245.67   9   51   81  10  0.936170   KT      3
강민호   842.00   8  660   48   7  0.988827   삼성      1
강백호   622.66   3  140    6   1  0.979866   KT      5
..       ...  ..  ...  ...  ..       ...  ...    ...
허정협   107.00   0   19    0   0  1.000000   키움      2
홍창기    52.00   0   12    1   0  1.000000   LG      3
황대인    48.00   0   40    4   6  1.000000  KIA      2
황윤호   297.67   6   49   81  14  0.955882  KIA      3
황재균  1026.67  11  127  233  27  0.970350   KT      3

[220 rows x 8 columns]

In [6]:
## 공격만 있는 선수 제외
on_atk = saber.index.drop(A_list)
saber_2 = saber.drop(on_atk)
saber_2 = saber_2.sort_index()
saber_2

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,SECA,TA,RC,RC27,XR,ISO,PSR,wOBA,BABIP,OW%
Name,,,,,,,,,,,,,,,,,,,,,
강경학,135,113,12,21,27,4,0,0,1,2,...,0.19469,0.54945,8.07651,0.29913,11.424,0.03540,0.00000,2.01068,0.32927,0.16759
강로한,306,288,25,38,69,15,6,4,7,1,...,0.28819,0.58744,18.35658,0.67987,29.914,0.13542,5.09091,0.93995,0.36517,0.50980
강민국,94,88,7,12,24,0,1,0,2,0,...,0.125,0.51515,7.37317,0.27308,8.304,0.02273,0.00000,2.67990,0.33803,0.14368
강민호,393,346,45,36,81,20,0,13,0,0,...,0.36127,0.66423,34.55274,1.27973,44.622,0.17052,0.00000,0.84588,0.26154,0.78654
강백호,505,438,65,72,147,29,1,13,9,5,...,0.40639,0.94137,77.96287,2.88751,84.244,0.15982,10.63636,0.70550,0.39181,0.94939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
허정협,77,68,8,3,16,1,0,0,0,0,...,0.13235,0.47170,4.09778,0.15177,6.108,0.01471,NaN,3.30656,0.32000,0.04927
홍창기,26,24,0,3,6,2,0,0,3,0,...,0.33333,0.68421,1.25657,0.04654,2.574,0.08333,0.00000,9.68285,0.50000,0.00485
황대인,28,25,0,0,5,2,0,0,0,0,...,0.2,0.50000,1.18714,0.04397,2.096,0.08000,NaN,9.01700,0.29412,0.00433
황윤호,130,123,9,9,37,5,2,1,2,2,...,0.20325,0.62222,14.46329,0.53568,14.874,0.09756,1.33333,2.01374,0.32432,0.39233
황재균,507,448,67,78,127,16,3,20,10,7,...,0.39286,0.80769,65.62606,2.43059,73.872,0.18304,13.33333,0.68693,0.29558,0.93003

In [7]:
saber_2['FPCT'] = df_2['FPCT']
saber_2

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,TA,RC,RC27,XR,ISO,PSR,wOBA,BABIP,OW%,FPCT
Name,,,,,,,,,,,,,,,,,,,,,
강경학,135,113,12,21,27,4,0,0,1,2,...,0.54945,8.07651,0.29913,11.424,0.03540,0.00000,2.01068,0.32927,0.16759,0.979275
강로한,306,288,25,38,69,15,6,4,7,1,...,0.58744,18.35658,0.67987,29.914,0.13542,5.09091,0.93995,0.36517,0.50980,0.947090
강민국,94,88,7,12,24,0,1,0,2,0,...,0.51515,7.37317,0.27308,8.304,0.02273,0.00000,2.67990,0.33803,0.14368,0.936170
강민호,393,346,45,36,81,20,0,13,0,0,...,0.66423,34.55274,1.27973,44.622,0.17052,0.00000,0.84588,0.26154,0.78654,0.988827
강백호,505,438,65,72,147,29,1,13,9,5,...,0.94137,77.96287,2.88751,84.244,0.15982,10.63636,0.70550,0.39181,0.94939,0.979866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
허정협,77,68,8,3,16,1,0,0,0,0,...,0.47170,4.09778,0.15177,6.108,0.01471,NaN,3.30656,0.32000,0.04927,1.000000
홍창기,26,24,0,3,6,2,0,0,3,0,...,0.68421,1.25657,0.04654,2.574,0.08333,0.00000,9.68285,0.50000,0.00485,1.000000
황대인,28,25,0,0,5,2,0,0,0,0,...,0.50000,1.18714,0.04397,2.096,0.08000,NaN,9.01700,0.29412,0.00433,1.000000
황윤호,130,123,9,9,37,5,2,1,2,2,...,0.62222,14.46329,0.53568,14.874,0.09756,1.33333,2.01374,0.32432,0.39233,0.955882
황재균,507,448,67,78,127,16,3,20,10,7,...,0.80769,65.62606,2.43059,73.872,0.18304,13.33333,0.68693,0.29558,0.93003,0.970350

In [8]:
saber_2['팀명'] = df_2['팀명']
saber_2

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,RC,RC27,XR,ISO,PSR,wOBA,BABIP,OW%,FPCT,팀명
Name,,,,,,,,,,,,,,,,,,,,,
강경학,135,113,12,21,27,4,0,0,1,2,...,8.07651,0.29913,11.424,0.03540,0.00000,2.01068,0.32927,0.16759,0.979275,한화
강로한,306,288,25,38,69,15,6,4,7,1,...,18.35658,0.67987,29.914,0.13542,5.09091,0.93995,0.36517,0.50980,0.947090,롯데
강민국,94,88,7,12,24,0,1,0,2,0,...,7.37317,0.27308,8.304,0.02273,0.00000,2.67990,0.33803,0.14368,0.936170,KT
강민호,393,346,45,36,81,20,0,13,0,0,...,34.55274,1.27973,44.622,0.17052,0.00000,0.84588,0.26154,0.78654,0.988827,삼성
강백호,505,438,65,72,147,29,1,13,9,5,...,77.96287,2.88751,84.244,0.15982,10.63636,0.70550,0.39181,0.94939,0.979866,KT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
허정협,77,68,8,3,16,1,0,0,0,0,...,4.09778,0.15177,6.108,0.01471,NaN,3.30656,0.32000,0.04927,1.000000,키움
홍창기,26,24,0,3,6,2,0,0,3,0,...,1.25657,0.04654,2.574,0.08333,0.00000,9.68285,0.50000,0.00485,1.000000,LG
황대인,28,25,0,0,5,2,0,0,0,0,...,1.18714,0.04397,2.096,0.08000,NaN,9.01700,0.29412,0.00433,1.000000,KIA
황윤호,130,123,9,9,37,5,2,1,2,2,...,14.46329,0.53568,14.874,0.09756,1.33333,2.01374,0.32432,0.39233,0.955882,KIA
황재균,507,448,67,78,127,16,3,20,10,7,...,65.62606,2.43059,73.872,0.18304,13.33333,0.68693,0.29558,0.93003,0.970350,KT

In [9]:
saber_2 = saber_2[saber_2['PA'] >= 100]
saber_2

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,RC,RC27,XR,ISO,PSR,wOBA,BABIP,OW%,FPCT,팀명
Name,,,,,,,,,,,,,,,,,,,,,
강경학,135,113,12,21,27,4,0,0,1,2,...,8.07651,0.29913,11.424,0.03540,0.00000,2.01068,0.32927,0.16759,0.979275,한화
강로한,306,288,25,38,69,15,6,4,7,1,...,18.35658,0.67987,29.914,0.13542,5.09091,0.93995,0.36517,0.50980,0.947090,롯데
강민호,393,346,45,36,81,20,0,13,0,0,...,34.55274,1.27973,44.622,0.17052,0.00000,0.84588,0.26154,0.78654,0.988827,삼성
강백호,505,438,65,72,147,29,1,13,9,5,...,77.96287,2.88751,84.244,0.15982,10.63636,0.70550,0.39181,0.94939,0.979866,KT
강진성,104,97,14,11,24,4,1,2,2,1,...,6.77232,0.25083,8.770,0.12371,2.00000,2.52052,0.29333,0.12400,0.962963,NC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
한승택,288,251,27,22,56,9,1,3,1,0,...,13.62514,0.50463,22.804,0.07968,1.50000,1.01559,0.31548,0.36426,0.991681,KIA
허경민,540,475,60,71,137,25,1,4,11,5,...,59.66739,2.2099,63.402,0.08211,5.86667,0.60320,0.29821,0.91658,0.972509,두산
허일,162,149,17,14,38,4,0,1,2,1,...,12.49533,0.46279,14.696,0.04698,1.33333,1.62984,0.30833,0.32518,0.977273,롯데
황윤호,130,123,9,9,37,5,2,1,2,2,...,14.46329,0.53568,14.874,0.09756,1.33333,2.01374,0.32432,0.39233,0.955882,KIA
황재균,507,448,67,78,127,16,3,20,10,7,...,65.62606,2.43059,73.872,0.18304,13.33333,0.68693,0.29558,0.93003,0.970350,KT

In [11]:
saber_2.columns

Index(['PA', 'AB', 'RBI', 'RUN', 'HIT', 'H2', 'H3', 'HR', 'SB', 'CS', 'SH',
       'SF', 'BB', 'IB', 'HP', 'KK', 'GD', 'ERR', 'LOB', 'P_HRA_RT', 'P_AB_CN',
       'P_HIT_CN', 'Position', 'Money_19', 'Money_20', 'OBP', 'SLG', 'OPS',
       'GPA', 'SECA', 'TA', 'RC', 'RC27', 'XR', 'ISO', 'PSR', 'wOBA', 'BABIP',
       'OW%', 'FPCT', '팀명'],
      dtype='object')

In [12]:
saber_3 = saber_2.drop(columns = ['팀명', 'Position'])
saber_3

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,TA,RC,RC27,XR,ISO,PSR,wOBA,BABIP,OW%,FPCT
Name,,,,,,,,,,,,,,,,,,,,,
강경학,135,113,12,21,27,4,0,0,1,2,...,0.54945,8.07651,0.29913,11.424,0.03540,0.00000,2.01068,0.32927,0.16759,0.979275
강로한,306,288,25,38,69,15,6,4,7,1,...,0.58744,18.35658,0.67987,29.914,0.13542,5.09091,0.93995,0.36517,0.50980,0.947090
강민호,393,346,45,36,81,20,0,13,0,0,...,0.66423,34.55274,1.27973,44.622,0.17052,0.00000,0.84588,0.26154,0.78654,0.988827
강백호,505,438,65,72,147,29,1,13,9,5,...,0.94137,77.96287,2.88751,84.244,0.15982,10.63636,0.70550,0.39181,0.94939,0.979866
강진성,104,97,14,11,24,4,1,2,2,1,...,0.56250,6.77232,0.25083,8.770,0.12371,2.00000,2.52052,0.29333,0.12400,0.962963
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
한승택,288,251,27,22,56,9,1,3,1,0,...,0.51724,13.62514,0.50463,22.804,0.07968,1.50000,1.01559,0.31548,0.36426,0.991681
허경민,540,475,60,71,137,25,1,4,11,5,...,0.66295,59.66739,2.2099,63.402,0.08211,5.86667,0.60320,0.29821,0.91658,0.972509
허일,162,149,17,14,38,4,0,1,2,1,...,0.53097,12.49533,0.46279,14.696,0.04698,1.33333,1.62984,0.30833,0.32518,0.977273
황윤호,130,123,9,9,37,5,2,1,2,2,...,0.62222,14.46329,0.53568,14.874,0.09756,1.33333,2.01374,0.32432,0.39233,0.955882
황재균,507,448,67,78,127,16,3,20,10,7,...,0.80769,65.62606,2.43059,73.872,0.18304,13.33333,0.68693,0.29558,0.93003,0.970350

In [13]:
scaled_saber = MinMaxScaler().fit_transform(saber_3)
scaled_saber = pd.DataFrame(scaled_saber)
scaled_saber.columns = saber_3.columns
scaled_saber.index = saber_3.index
scaled_saber['Money_20'] = saber_3['Money_20']
scaled_saber['Money_19'] = saber_3['Money_19']
scaled_saber

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,TA,RC,RC27,XR,ISO,PSR,wOBA,BABIP,OW%,FPCT
Name,,,,,,,,,,,,,,,,,,,,,
강경학,0.058935,0.051440,0.089109,0.157407,0.072626,0.105263,0.0,0.000000,0.025641,0.2,...,0.269891,0.147501,0.147501,0.070355,0.056198,0.000000,0.698606,0.459137,0.169825,0.749411
강로한,0.384030,0.411523,0.217822,0.314815,0.307263,0.394737,0.6,0.121212,0.179487,0.1,...,0.311902,0.246811,0.246810,0.250083,0.441989,0.211106,0.192360,0.591297,0.525534,0.360269
강민호,0.549430,0.530864,0.415842,0.296296,0.374302,0.526316,0.0,0.393939,0.000000,0.0,...,0.396820,0.403274,0.403273,0.393048,0.577374,0.000000,0.147884,0.209800,0.813191,0.864906
강백호,0.762357,0.720165,0.613861,0.629630,0.743017,0.763158,0.1,0.393939,0.230769,0.5,...,0.703292,0.822636,0.822634,0.778184,0.536103,0.441061,0.081511,0.689368,0.982465,0.756559
강진성,0.000000,0.018519,0.108911,0.064815,0.055866,0.105263,0.1,0.060606,0.051282,0.1,...,0.284323,0.134902,0.134903,0.044558,0.396822,0.082935,0.939661,0.326830,0.124515,0.552189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
한승택,0.349810,0.335391,0.237624,0.166667,0.234637,0.236842,0.1,0.090909,0.025641,0.0,...,0.234272,0.201104,0.201102,0.180972,0.226992,0.062201,0.228123,0.408371,0.374253,0.899410
허경민,0.828897,0.796296,0.564356,0.620370,0.687151,0.657895,0.1,0.121212,0.282051,0.5,...,0.395404,0.645893,0.645891,0.575594,0.236365,0.243275,0.033144,0.344795,0.948360,0.667604
허일,0.110266,0.125514,0.138614,0.092593,0.134078,0.105263,0.0,0.030303,0.051282,0.1,...,0.249455,0.190189,0.190189,0.102160,0.100864,0.055290,0.518543,0.382050,0.333631,0.725207
황윤호,0.049430,0.072016,0.059406,0.046296,0.128492,0.131579,0.2,0.030303,0.051282,0.2,...,0.350363,0.209200,0.209201,0.103890,0.295958,0.055290,0.700053,0.440914,0.403430,0.466578
황재균,0.766160,0.740741,0.633663,0.685185,0.631285,0.421053,0.3,0.606061,0.256410,0.7,...,0.555463,0.703456,0.703454,0.677365,0.625665,0.552897,0.072731,0.335113,0.962341,0.641509

In [64]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\전처리')
scaled_saber.to_csv('2019_타자_투입(타석 100이상, MinMax)_산출(20연봉).csv', encoding = 'cp949')

In [14]:
df_fin = saber_2.iloc[:, 27:]
df_fin = df_fin.drop(columns = ['GPA', 'SECA', 'TA', 'RC', 'RC27', 'ISO', 'PSR', 'wOBA', 'BABIP', 'OW%'])
df_fin['팀명'] = df_2['팀명']
df_fin['20연봉'] = saber_2['Money_20']
df_fin

          OPS      XR      FPCT   팀명
Name
강경학   0.61525  11.424  0.979275   한화
강로한   0.65369  29.914  0.947090   롯데
강민호   0.71920  44.622  0.988827   삼성
강백호   0.91128  84.244  0.979866   KT
강진성   0.66921   8.770  0.962963   NC
...       ...     ...       ...  ...
한승택   0.60172  22.804  0.991681  KIA
허경민   0.72062  63.402  0.972509   두산
허일    0.61683  14.696  0.977273   롯데
황윤호   0.72396  14.874  0.955882  KIA
황재균   0.82352  73.872  0.970350   KT

[122 rows x 4 columns]

In [168]:
df_fin = df_fin.replace(np.nan, 0)

In [170]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\전처리')
df_fin.to_csv('2019_타자_투입(OPS, XR, FPCT)_산출(20연봉).csv', encoding = 'cp949')

In [15]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\수비율\전처리')
df_df = pd.read_csv('2019_전포지션_수비점수_March_kWAR_AHP.csv', encoding = 'cp949')
df_df.index = df_df['선수명']
del df_df['선수명']
df_df

          IP     E  March_score  kWAR_score  AHP_score
선수명
강경학   273.00   4.0     1468.641     147.829     39.993
강로한   709.67  20.0     3910.467     449.717    105.735
강민국   245.67   9.0     1487.254     171.306     44.404
강민호   842.00   8.0     6661.904     832.738    308.113
강백호   622.66   3.0     1549.272     127.421     23.109
..       ...   ...          ...         ...        ...
홍창기    52.00   0.0      136.500      13.400      2.337
황대인    48.00   0.0      100.000       1.200      1.260
황윤호   297.67   6.0     1534.647     177.799     38.623
황재균  1026.67  11.0     4123.564     602.866    127.589
황진수    10.33   0.0       37.320       5.598      1.157

[281 rows x 5 columns]

In [21]:
kWAR = []
March = []
AHP = []
for sa in range(0, len(saber_2)) :
    for df in range(0, len(df_df)) :
        if saber_2.index[sa] == df_df.index[df] :
            kWAR.append(df_df['kWAR_score'][df])
            March.append(df_df['March_score'][df])
            AHP.append(df_df['AHP_score'][df])

In [23]:
saber_2['kWAR_score'] = kWAR
saber_2['March_score'] = March
saber_2['AHP_score'] = AHP
saber_2

<ipython-input-23-62554496fb0e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  saber_2['kWAR_score'] = kWAR
<ipython-input-23-62554496fb0e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  saber_2['March_score'] = March
<ipython-input-23-62554496fb0e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  saber_2['AHP_score'] = AHP

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,ISO,PSR,wOBA,BABIP,OW%,FPCT,팀명,kWAR_score,March_score,AHP_score
Name,,,,,,,,,,,,,,,,,,,,,
강경학,135,113,12,21,27,4,0,0,1,2,...,0.03540,0.00000,2.01068,0.32927,0.16759,0.979275,한화,147.829,1468.641,39.993
강로한,306,288,25,38,69,15,6,4,7,1,...,0.13542,5.09091,0.93995,0.36517,0.50980,0.947090,롯데,449.717,3910.467,105.735
강민호,393,346,45,36,81,20,0,13,0,0,...,0.17052,0.00000,0.84588,0.26154,0.78654,0.988827,삼성,832.738,6661.904,308.113
강백호,505,438,65,72,147,29,1,13,9,5,...,0.15982,10.63636,0.70550,0.39181,0.94939,0.979866,KT,127.421,1549.272,23.109
강진성,104,97,14,11,24,4,1,2,2,1,...,0.12371,2.00000,2.52052,0.29333,0.12400,0.962963,NC,26.609,276.607,4.790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
한승택,288,251,27,22,56,9,1,3,1,0,...,0.07968,1.50000,1.01559,0.31548,0.36426,0.991681,KIA,696.384,5571.072,257.662
허경민,540,475,60,71,137,25,1,4,11,5,...,0.08211,5.86667,0.60320,0.29821,0.91658,0.972509,두산,631.056,4211.040,130.418
허일,162,149,17,14,38,4,0,1,2,1,...,0.04698,1.33333,1.62984,0.30833,0.32518,0.977273,롯데,46.765,465.352,8.300
황윤호,130,123,9,9,37,5,2,1,2,2,...,0.09756,1.33333,2.01374,0.32432,0.39233,0.955882,KIA,177.799,1534.647,38.623
황재균,507,448,67,78,127,16,3,20,10,7,...,0.18304,13.33333,0.68693,0.29558,0.93003,0.970350,KT,602.866,4123.564,127.589

In [24]:
saber_2.sort_values(by = ['kWAR_score'], ascending = False)

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,ISO,PSR,wOBA,BABIP,OW%,FPCT,팀명,kWAR_score,March_score,AHP_score
Name,,,,,,,,,,,,,,,,,,,,,
박세혁,505,441,63,58,123,19,9,4,8,2,...,0.11111,5.33333,0.63423,0.31733,0.90959,0.990577,두산,1062.025,8496.200,392.949
이재원,502,451,75,33,121,19,0,12,1,0,...,0.12195,1.84615,0.65395,0.28165,0.88642,0.993704,SK,1034.754,8278.032,382.859
최재훈,451,373,31,47,108,18,0,3,3,10,...,0.07239,3.00000,0.72923,0.33546,0.88908,0.993103,한화,1015.511,8124.090,375.739
유강남,468,418,49,44,113,22,0,16,0,0,...,0.16746,0.00000,0.72869,0.29755,0.87266,0.991515,LG,960.583,7684.667,355.416
장성우,413,366,41,25,96,7,0,7,0,1,...,0.07650,0.00000,0.72699,0.31900,0.76196,0.992701,KT,905.288,7242.306,334.957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
채태인,182,167,29,11,42,11,0,5,0,0,...,0.15569,0.00000,1.55193,0.31092,0.38374,0.997253,롯데,0.000,682.606,7.509
오재일,529,467,102,76,137,29,1,21,2,1,...,0.20128,3.65217,0.69923,0.33048,0.94344,0.996400,두산,0.000,2079.648,22.876
이대호,549,485,88,48,138,23,1,16,0,0,...,0.15052,0.00000,0.63907,0.29684,0.93003,0.993671,롯데,0.000,293.568,3.229
김태균,500,433,62,47,132,21,0,6,3,0,...,0.09007,4.00000,0.65637,0.36950,0.91055,0.995349,한화,0.000,444.427,4.889
유민상,202,175,26,23,51,15,0,5,0,0,...,0.17143,0.00000,1.46732,0.34074,0.67713,0.990132,KIA,0.000,564.300,6.207

In [25]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\전처리')
saber_2.to_csv('2019_타자_투입(타석 100이상, 수비점수)_산출(19연봉).csv', encoding = 'cp949')

In [20]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\전처리')
df_temp = pd.read_csv('2019_타자_투입(타석 100이상, 수비점수)_산출(19연봉).csv', encoding = 'cp949')
df_temp.index = df_temp['Name']
del df_temp['Name']
df_temp = df_temp.drop(columns = ['팀명', 'Position'])
df_temp

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,XR,ISO,PSR,wOBA,BABIP,OW%,FPCT,kWAR_score,March_score,AHP_score
Name,,,,,,,,,,,,,,,,,,,,,
강경학,135,113,12,21,27,4,0,0,1,2,...,11.424,0.03540,0.00000,2.01068,0.32927,0.16759,0.979275,290.201,2884.098,50.647
강로한,306,288,25,38,69,15,6,4,7,1,...,29.914,0.13542,5.09091,0.93995,0.36517,0.50980,0.947090,785.830,6602.337,206.309
강민호,393,346,45,36,81,20,0,13,0,0,...,44.622,0.17052,0.00000,0.84588,0.26154,0.78654,0.988827,702.721,7027.212,145.229
강백호,505,438,65,72,147,29,1,13,9,5,...,84.244,0.15982,10.63636,0.70550,0.39181,0.94939,0.979866,420.339,3690.130,70.483
강진성,104,97,14,11,24,4,1,2,2,1,...,8.770,0.12371,2.00000,2.52052,0.29333,0.12400,0.962963,661.361,4409.072,136.681
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
한승택,288,251,27,22,56,9,1,3,1,0,...,22.804,0.07968,1.50000,1.01559,0.31548,0.36426,0.991681,72.398,664.480,12.230
허경민,540,475,60,71,137,25,1,4,11,5,...,63.402,0.08211,5.86667,0.60320,0.29821,0.91658,0.972509,298.172,2385.373,110.324
허일,162,149,17,14,38,4,0,1,2,1,...,14.696,0.04698,1.33333,1.62984,0.30833,0.32518,0.977273,27.000,301.000,4.840
황윤호,130,123,9,9,37,5,2,1,2,2,...,14.874,0.09756,1.33333,2.01374,0.32432,0.39233,0.955882,233.876,1871.008,86.534
황재균,507,448,67,78,127,16,3,20,10,7,...,73.872,0.18304,13.33333,0.68693,0.29558,0.93003,0.970350,26.609,276.607,4.790

In [21]:
scaled_df_temp = pd.DataFrame(StandardScaler().fit_transform(df_temp))
scaled_df_temp.index = df_temp.index
scaled_df_temp.columns = df_temp.columns
scaled_df_temp

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,XR,ISO,PSR,wOBA,BABIP,OW%,FPCT,kWAR_score,March_score,AHP_score
Name,,,,,,,,,,,,,,,,,,,,,
강경학,-1.448857,-1.507465,-1.153805,-0.891512,-1.364532,-1.311045,-0.715248,-0.974522,-0.719673,-0.248727,...,-1.236208,-1.406984,-0.890103,1.633049,0.584285,-1.588383,-0.235323,-0.114752,-0.019486,-0.373332
강로한,-0.376783,-0.254423,-0.624922,-0.196139,-0.424387,-0.001951,2.069653,-0.359300,0.017111,-0.618784,...,-0.526250,0.493005,0.378653,-0.222707,1.509420,-0.468870,-2.430866,1.668942,1.687615,1.340021
강민호,0.168658,0.160871,0.188744,-0.277948,-0.155774,0.593092,-0.715248,1.024950,-0.842470,-0.988842,...,0.038491,1.159767,-0.890103,-0.385746,-1.161101,0.436463,0.416301,1.369845,1.882682,0.667721
강백호,0.870835,0.819613,1.002410,1.194606,1.321598,1.664169,-0.251098,1.024950,0.262706,0.861445,...,1.559851,0.956509,1.760689,-0.629048,2.195927,0.969214,-0.194995,0.353595,0.350576,-0.155000
강진성,-1.643210,-1.622029,-1.072439,-1.300555,-1.431685,-1.311045,-0.251098,-0.666911,-0.596875,-0.618784,...,-1.338113,0.270560,-0.391663,2.516688,-0.341880,-1.730984,-1.348056,1.220997,0.680653,0.573634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
한승택,-0.489633,-0.519352,-0.543556,-0.850608,-0.715384,-0.716002,-0.251098,-0.513105,-0.719673,-0.988842,...,-0.799252,-0.565837,-0.516273,-0.091610,0.228920,-0.944993,0.610973,-0.898593,-1.038547,-0.796183
허경민,1.090266,1.084541,0.798994,1.153702,1.097754,1.188135,-0.251098,-0.359300,0.508300,0.861445,...,0.759583,-0.519677,0.571988,-0.806351,-0.216124,0.861878,-0.696881,-0.086066,-0.248458,0.283526
허일,-1.279582,-1.249697,-0.950389,-1.177842,-1.118303,-1.311045,-0.715248,-0.820717,-0.596875,-0.618784,...,-1.110574,-1.187009,-0.557811,0.972989,0.044666,-1.072840,-0.371885,-1.061973,-1.205426,-0.877524
황윤호,-1.480204,-1.435863,-1.275855,-1.382364,-1.140688,-1.192037,0.213053,-0.820717,-0.596875,-0.248727,...,-1.103739,-0.226187,-0.557811,1.638353,0.456725,-0.853164,-1.831074,-0.317457,-0.484611,0.021672
황재균,0.883374,0.891215,1.083777,1.440032,0.873910,0.117058,0.677203,2.101589,0.385503,1.601560,...,1.161599,1.397598,2.432827,-0.661233,-0.283898,0.905879,-0.844106,-1.063380,-1.216626,-0.878074

In [23]:
scaled_df_temp['Money_20'] = np.log(df_temp['Money_20'])
scaled_df_temp['Money_19'] = np.log(df_temp['Money_19'])
scaled_df_temp

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,XR,ISO,PSR,wOBA,BABIP,OW%,FPCT,kWAR_score,March_score,AHP_score
Name,,,,,,,,,,,,,,,,,,,,,
강경학,-1.448857,-1.507465,-1.153805,-0.891512,-1.364532,-1.311045,-0.715248,-0.974522,-0.719673,-0.248727,...,-1.236208,-1.406984,-0.890103,1.633049,0.584285,-1.588383,-0.235323,-0.114752,-0.019486,-0.373332
강로한,-0.376783,-0.254423,-0.624922,-0.196139,-0.424387,-0.001951,2.069653,-0.359300,0.017111,-0.618784,...,-0.526250,0.493005,0.378653,-0.222707,1.509420,-0.468870,-2.430866,1.668942,1.687615,1.340021
강민호,0.168658,0.160871,0.188744,-0.277948,-0.155774,0.593092,-0.715248,1.024950,-0.842470,-0.988842,...,0.038491,1.159767,-0.890103,-0.385746,-1.161101,0.436463,0.416301,1.369845,1.882682,0.667721
강백호,0.870835,0.819613,1.002410,1.194606,1.321598,1.664169,-0.251098,1.024950,0.262706,0.861445,...,1.559851,0.956509,1.760689,-0.629048,2.195927,0.969214,-0.194995,0.353595,0.350576,-0.155000
강진성,-1.643210,-1.622029,-1.072439,-1.300555,-1.431685,-1.311045,-0.251098,-0.666911,-0.596875,-0.618784,...,-1.338113,0.270560,-0.391663,2.516688,-0.341880,-1.730984,-1.348056,1.220997,0.680653,0.573634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
한승택,-0.489633,-0.519352,-0.543556,-0.850608,-0.715384,-0.716002,-0.251098,-0.513105,-0.719673,-0.988842,...,-0.799252,-0.565837,-0.516273,-0.091610,0.228920,-0.944993,0.610973,-0.898593,-1.038547,-0.796183
허경민,1.090266,1.084541,0.798994,1.153702,1.097754,1.188135,-0.251098,-0.359300,0.508300,0.861445,...,0.759583,-0.519677,0.571988,-0.806351,-0.216124,0.861878,-0.696881,-0.086066,-0.248458,0.283526
허일,-1.279582,-1.249697,-0.950389,-1.177842,-1.118303,-1.311045,-0.715248,-0.820717,-0.596875,-0.618784,...,-1.110574,-1.187009,-0.557811,0.972989,0.044666,-1.072840,-0.371885,-1.061973,-1.205426,-0.877524
황윤호,-1.480204,-1.435863,-1.275855,-1.382364,-1.140688,-1.192037,0.213053,-0.820717,-0.596875,-0.248727,...,-1.103739,-0.226187,-0.557811,1.638353,0.456725,-0.853164,-1.831074,-0.317457,-0.484611,0.021672
황재균,0.883374,0.891215,1.083777,1.440032,0.873910,0.117058,0.677203,2.101589,0.385503,1.601560,...,1.161599,1.397598,2.432827,-0.661233,-0.283898,0.905879,-0.844106,-1.063380,-1.216626,-0.878074

In [24]:
scaled_df_temp.to_csv('2019_타자_투입(stand, 타석 100이상, 수비점수)_산출(log, 19연봉).csv', encoding = 'cp949')

In [27]:
df_temp.sort_values(by = ['kWAR_score'], ascending = False)

,PA,AB,RBI,RUN,HIT,H2,H3,HR,SB,CS,...,XR,ISO,PSR,wOBA,BABIP,OW%,FPCT,kWAR_score,March_score,AHP_score
Name,,,,,,,,,,,,,,,,,,,,,
김태진,399,374,46,44,103,14,5,5,12,4,...,43.914,0.10428,7.05882,0.73137,0.32131,0.81510,0.988048,1062.025,8496.200,392.949
김헌곤,467,411,46,57,122,20,1,5,10,8,...,54.512,0.09002,6.66667,0.68263,0.31536,0.89070,1.000000,1034.754,8278.032,382.859
박계범,204,168,25,26,43,8,1,4,5,1,...,24.470,0.13095,4.44444,1.44116,0.31967,0.52363,0.952880,1015.511,8124.090,375.739
노진혁,390,348,43,51,92,23,2,13,0,1,...,50.160,0.18966,0.00000,0.85462,0.30620,0.83620,0.985876,960.583,7684.667,355.416
손아섭,568,512,63,78,151,22,1,10,13,8,...,73.324,0.10547,11.30435,0.58872,0.34223,0.93117,0.984674,905.288,7242.306,334.957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
김성욱,333,287,36,38,66,16,1,9,6,4,...,36.398,0.15679,7.20000,0.95659,0.26636,0.68147,0.989796,0.000,1802.460,19.827
오재일,529,467,102,76,137,29,1,21,2,1,...,83.968,0.20128,3.65217,0.69923,0.33048,0.94344,0.996400,0.000,1080.190,11.882
김형준,119,107,9,13,24,5,0,2,0,0,...,9.828,0.10280,0.00000,2.29543,0.27160,0.13858,0.995816,0.000,444.427,4.889
김문호,109,103,4,6,25,7,0,0,2,0,...,8.540,0.06796,0.00000,2.40291,0.33784,0.07935,0.974359,0.000,293.568,3.229
정의윤,419,380,59,44,107,24,0,13,0,0,...,55.510,0.16579,0.00000,0.79289,0.30421,0.88404,0.985714,0.000,682.606,7.509